In [2]:
import os
embedding_dim = 50
filepath = '/Users/Moon/Desktop/Summer/NLP/pytest/'
os.chdir(filepath)
#print('현재 디렉토리', os.getcwd())

In [3]:
with open('wiki_test.txt', 'r', encoding = 'utf-8') as f:
    data = f.read()


import rhinoMorph
from nltk.tokenize import sent_tokenize
import nltk
# nltk.download('punkt') 설치되었는지 안되었는지 모름
sent_data = sent_tokenize(data)
rn = rhinoMorph.startRhino()

filepath:  /Users/Moon/opt/anaconda3/lib/python3.7/site-packages
classpath:  /Users/Moon/opt/anaconda3/lib/python3.7/site-packages/rhinoMorph/lib/rhino.jar
RHINO started!


In [5]:
print(type(sent_data))
print(len(sent_data))
print(sent_data[:10]) 
#전체주석 까먹음 command + /
#구동이 잘되는것을 확인

total_lines = len(sent_data)
cnt = 0
with open(filepath + 'wiki202007_nationalcorpus_naverratings_morphed.txt', 'w', encoding = 'utf-8') as f:
    for data_each in sent_data:
        morphed_data_each = rhinoMorph.onlyMorph_list(rn, data_each, pos = ['NNG', 'NNP', 'NP', 'VV', 'VA', 'XR', 'IC', 'MM', 'MAG', 'MAJ'])
        joined_data_each = ' '.join(morphed_data_each)
        if joined_data_each:
            f.write(joined_data_each + '\n')
        cnt += 1
        if (cnt % 1000) == 0:
            print(round(cnt/total_lines*100, 3),'%')
    print('완')
#위의 코드는 형태소분석을 한 내용을 띄어쓰기를 하여 영어와 같은 형식으로 변환을 한 다음 그것을 줄을 간격으로 하나씩 저장

<class 'list'>
11977
['<doc id="5" url="https://ko.wikipedia.org/wiki?curid=5" title="지미 카터">\n지미 카터\n\n제임스 얼 "지미" 카터 주니어(, 1924년 10월 1일 ~ )는 민주당 출신 미국 39번째 대통령 (1977년 ~ 1981년)이다.', '지미 카터는 조지아주 섬터 카운티 플레인스 마을에서 태어났다.', '조지아 공과대학교를 졸업하였다.', '그 후 해군에 들어가 전함·원자력·잠수함의 승무원으로 일하였다.', '1953년 미국 해군 대위로 예편하였고 이후 땅콩·면화 등을 가꿔 많은 돈을 벌었다.', '그의 별명이 "땅콩 농부" (Peanut Farmer)로 알려졌다.', '1962년 조지아 주 상원 의원 선거에서 낙선하나 그 선거가 부정선거 였음을 입증하게 되어 당선되고, 1966년 조지아 주 지사 선거에 낙선하지만 1970년 조지아 주 지사를 역임했다.', '대통령이 되기 전 조지아주 상원의원을 두번 연임했으며, 1971년부터 1975년까지 조지아 지사로 근무했다.', '조지아 주지사로 지내면서, 미국에 사는 흑인 등용법을 내세웠다.', '1976년 대통령 선거에 민주당 후보로 출마하여 도덕주의 정책으로 내세워, 포드를 누르고 당선되었다.']
8.349 %
16.699 %
25.048 %
33.397 %
41.747 %
50.096 %
58.445 %
66.795 %
75.144 %
83.493 %
91.843 %
완


In [6]:
def read_data(filename, encoding = 'utf-8'):
    with open(filename,'r', encoding=encoding) as f:
            data = [line.split(' ') for line in f.read().splitlines()]
    return data

data = read_data(filepath + 'wiki202007_nationalcorpus_naverratings_morphed.txt', 'utf-8')

# print(len(data))
# print(data[:3]) #구동확인

from gensim.models import Word2Vec
os.chdir(filepath + 'word2vec')

model = Word2Vec(sentences= data, size = embedding_dim, window= 10, min_count=5, workers= 4, sg=1)
#위에서 형태소분석한 단어들을 바탕으로 임베딩 레이어는 50개 최소단어빈도는 5, input은 data의 크기로 지정한 skipgram
model.save('embedding_window10_mincnt5_skipgram.model1')
print('모델 완')

모델 완


In [11]:
words = list(model.wv.vocab)
with open('embedding_window10_mincnt5_skipgram.txt', 'w') as f:
    for word in words:
        data = model.wv[word].tolist() #각 단어의 임베딩 값을 가져옴
        print(data[:2])
        
        data.insert(0, word )# 각 단어의 이름을 가져옴 
        print(data[:2])
        
        for item in data:
            f.write('%s' %item)
        f.write('\n')

[0.12461915612220764, 0.09661988168954849]
['미', 0.12461915612220764]
[0.017248203977942467, 0.43222421407699585]
['카터', 0.017248203977942467]
[0.07633312791585922, 0.34141096472740173]
['얼', 0.07633312791585922]
[-0.16154149174690247, 0.24631360173225403]
['민주당', -0.16154149174690247]
[-0.00814326573163271, 0.5378747582435608]
['출신', -0.00814326573163271]
[0.025665931403636932, -0.09937687963247299]
['미국', 0.025665931403636932]
[0.15471264719963074, 0.751875638961792]
['대통령', 0.15471264719963074]
[0.0353187620639801, 0.32605698704719543]
['조지아', 0.0353187620639801]
[-0.39100906252861023, 0.3679477572441101]
['마을', -0.39100906252861023]
[0.034148093312978745, 0.37500450015068054]
['태어나', 0.034148093312978745]
[-0.06076787784695625, 0.38021785020828247]
['공과대학', -0.06076787784695625]
[-0.017121514305472374, 0.38042593002319336]
['교', -0.017121514305472374]
[-0.027510525658726692, 0.4307747483253479]
['졸업', -0.027510525658726692]
[0.17343318462371826, 0.2790836989879608]
['그', 0.17343318

['보상', -0.0956428274512291]
[0.05017858371138573, 0.3410797417163849]
['결과적', 0.05017858371138573]
[0.012062379159033298, 0.1642380803823471]
['폭발적', 0.012062379159033298]
[-0.033418748527765274, 0.29736843705177307]
['자기', -0.033418748527765274]
[0.11945530772209167, 0.20130503177642822]
['상승', 0.11945530772209167]
[-0.14214061200618744, 0.3578891456127167]
['현상', -0.14214061200618744]
[-0.021866746246814728, 0.17731186747550964]
['재촉', -0.021866746246814728]
[0.05194665119051933, 0.3201444149017334]
['조차', 0.05194665119051933]
[-0.04076900705695152, 0.2749883830547333]
['거꾸로', -0.04076900705695152]
[-0.1850961446762085, 0.5183232426643372]
['높이', -0.1850961446762085]
[0.1564512997865677, 0.16188551485538483]
['낳', 0.1564512997865677]
[-0.00345787825062871, 0.33365362882614136]
['폐해', -0.00345787825062871]
[0.02187318168580532, 0.1915338784456253]
['얼마나', 0.02187318168580532]
[-0.23969431221485138, 0.30900341272354126]
['극심', -0.23969431221485138]
[0.06643414497375488, 0.2334922850131

['물들', -0.02601071633398533]
[0.023942111060023308, 0.42538338899612427]
['짧', 0.023942111060023308]
[0.08807633817195892, 0.43048450350761414]
['과도기', 0.08807633817195892]
[0.5086148381233215, 0.3371230661869049]
['가장', 0.5086148381233215]
[-0.31612858176231384, 0.48185813426971436]
['오른쪽', -0.31612858176231384]
[0.2627496123313904, 0.7259860038757324]
['역사', 0.2627496123313904]
[0.12187938392162323, 0.1456492841243744]
['목격', 0.12187938392162323]
[0.05609344318509102, 0.2714560627937317]
['러시아', 0.05609344318509102]
[-0.17607085406780243, 0.7931318283081055]
['공산주의', -0.17607085406780243]
[-0.13900825381278992, 0.07212121784687042]
['시간', -0.13900825381278992]
[0.0433700829744339, 0.4722819924354553]
['KBS', 0.0433700829744339]
[0.0039210328832268715, 0.4681476354598999]
['북', 0.0039210328832268715]
[-0.04666184261441231, 0.2689354419708252]
['망명', -0.04666184261441231]
[-0.17089496552944183, 0.4371480941772461]
['대화', -0.17089496552944183]
[-0.02261444181203842, 0.256300687789917]
[

[0.021993951871991158, 0.29113367199897766]
['들러리', 0.021993951871991158]
[-0.23346231877803802, 0.4391556680202484]
['세우', -0.23346231877803802]
[-0.06339001655578613, 0.3593379855155945]
['슬라브', -0.06339001655578613]
[-0.06343002617359161, 0.3446190357208252]
['민족주의', -0.06343002617359161]
[-0.024665752425789833, 0.5298498868942261]
['거대', -0.024665752425789833]
[0.009300357662141323, 0.5160842537879944]
['제국', 0.009300357662141323]
[0.10973846167325974, 0.4134487509727478]
['종말', 0.10973846167325974]
[-0.003198434831574559, 0.2699005901813507]
['다가가', -0.003198434831574559]
[-0.01899026148021221, 0.42066511511802673]
['우크라이나', -0.01899026148021221]
[-0.05035528168082237, 0.6782544255256653]
['공화국', -0.05035528168082237]
[-0.07567911595106125, 0.25268828868865967]
['별도', -0.07567911595106125]
[-0.05700945109128952, 0.4666026830673218]
['독립국가', -0.05700945109128952]
[-0.28099486231803894, 0.6755642890930176]
['연방', -0.28099486231803894]
[0.038571249693632126, 0.47074469923973083]
['창설

[-0.13543587923049927, 0.7961909770965576]
['태', -0.13543587923049927]
[-0.21732643246650696, -0.14533035457134247]
['원유', -0.21732643246650696]
[-0.002463880693539977, 0.07230894267559052]
['수급', -0.002463880693539977]
[0.02743438072502613, 0.15852989256381989]
['정상', 0.02743438072502613]
[-0.14064984023571014, 0.11921681463718414]
['일분', -0.14064984023571014]
[-0.2575726807117462, 0.4408762753009796]
['전쟁', -0.2575726807117462]
[-0.4097640812397003, 0.1947178840637207]
['장기화', -0.4097640812397003]
[-0.05452574044466019, 0.1367214322090149]
['유류', -0.05452574044466019]
[-0.02725548855960369, 0.3473448157310486]
['페르시아만', -0.02725548855960369]
[-0.032073140144348145, 0.3456819951534271]
['정쟁', -0.032073140144348145]
[-0.1486741006374359, 0.29927533864974976]
['발발', -0.1486741006374359]
[-0.16829729080200195, 0.08896631747484207]
['차질', -0.16829729080200195]
[-0.04094225540757179, 0.11228734254837036]
['순조', -0.04094225540757179]
[0.07783734053373337, 0.12185731530189514]
['개전', 0.07783

['최종', -0.025044025853276253]
[-0.04358057305216789, 0.41930508613586426]
['확정', -0.04358057305216789]
[-0.331002414226532, 0.3285438120365143]
['납부', -0.331002414226532]
[-0.08721589297056198, 0.1467314511537552]
['원양', -0.08721589297056198]
[-0.09200933575630188, -0.026348236948251724]
['모', -0.09200933575630188]
[-0.00905223935842514, 0.10844642668962479]
['식품', -0.00905223935842514]
[-0.027994941920042038, 0.39154061675071716]
['발돋움', -0.027994941920042038]
[-0.08672674000263214, 0.2616509795188904]
['카메라', -0.08672674000263214]
[0.17177660763263702, -0.1235475242137909]
['정밀', 0.17177660763263702]
[0.2265261858701706, 0.5802057385444641]
['부문', 0.2265261858701706]
[0.021199120208621025, 0.12291308492422104]
['부산수산대', 0.021199120208621025]
[0.12380146980285645, 0.6093589663505554]
['학', 0.12380146980285645]
[-0.06059134006500244, 0.3088834285736084]
['뛰어들', -0.06059134006500244]
[-0.11742649227380753, 0.13186845183372498]
['산업체', -0.11742649227380753]
[0.001985596725717187, 0.47174

['전후', 0.0645027682185173]
[0.025374576449394226, 0.30804991722106934]
['건재', 0.025374576449394226]
[-0.012094644829630852, 0.27884310483932495]
['간간이', -0.012094644829630852]
[-0.11605475097894669, 0.2914794981479645]
['경고', -0.11605475097894669]
[-0.026392128318548203, 0.22813251614570618]
['군사행동', -0.026392128318548203]
[-0.28664830327033997, 0.13171876966953278]
['재개', -0.28664830327033997]
[-0.044023238122463226, 0.279959499835968]
['고민', -0.044023238122463226]
[-0.12669117748737335, -0.12992382049560547]
['공격', -0.12669117748737335]
[-0.0949721708893776, 0.34655556082725525]
['아랍국', -0.0949721708893776]
[-0.08394519239664078, 0.38236352801322937]
['따뜻하', -0.08394519239664078]
[-0.052013225853443146, 0.3371431231498718]
['시선', -0.052013225853443146]
[0.049149442464113235, 0.05406511574983597]
['가하', 0.049149442464113235]
[-0.01021153200417757, 0.2974538505077362]
['처벌', -0.01021153200417757]
[0.03783133998513222, -0.004066184628754854]
['충분', 0.03783133998513222]
[0.03954581171274

['선의', -0.01656731404364109]
[-0.140757218003273, 0.4962466359138489]
['용', -0.140757218003273]
[0.08190874010324478, 0.22196383774280548]
['처음', 0.08190874010324478]
[0.044840920716524124, 0.3483794629573822]
['연초', 0.044840920716524124]
[0.031861547380685806, 0.35584405064582825]
['낙관적', 0.031861547380685806]
[0.1636708676815033, 0.21430285274982452]
['비추', 0.1636708676815033]
[0.011887028813362122, 0.22208638489246368]
['팽창', 0.011887028813362122]
[0.13092239201068878, 0.20590290427207947]
['실세', 0.13092239201068878]
[-0.08684173226356506, 0.1795036643743515]
['견디', -0.08684173226356506]
[0.13128116726875305, 0.20046661794185638]
['끼치', 0.13128116726875305]
[0.17589899897575378, 0.16047248244285583]
['장영자', 0.17589899897575378]
[0.35076576471328735, -0.20004607737064362]
['어음', 0.35076576471328735]
[0.0980210155248642, -0.03886878862977028]
['하청', 0.0980210155248642]
[0.12084277719259262, 0.19771163165569305]
['담당자', 0.12084277719259262]
[-0.08503725379705429, 0.20498667657375336]
[

[0.1117648184299469, 0.10102424770593643]
['광주고속', 0.1117648184299469]
[-0.007582422345876694, 0.3571605682373047]
['며칠', -0.007582422345876694]
[0.1169726774096489, 0.4886505901813507]
['목사', 0.1169726774096489]
[0.3930719196796417, 0.04604063928127289]
['세일', 0.3930719196796417]
[0.17580929398536682, 0.2901090085506439]
['일신', 0.17580929398536682]
[-0.02383788675069809, 0.27469003200531006]
['헌', -0.02383788675069809]
[-0.016803080216050148, 0.31118255853652954]
['약해', -0.016803080216050148]
[-0.11129079014062881, 0.11920333653688431]
['증설', -0.11129079014062881]
[-0.0001357704895781353, 0.3152225613594055]
['보람', -0.0001357704895781353]
[-0.03461501747369766, 0.26479431986808777]
['몫', -0.03461501747369766]
[-0.09835205227136612, 0.19323661923408508]
['덜', -0.09835205227136612]
[-0.10725607722997665, 0.32292625308036804]
['획기적', -0.10725607722997665]
[0.04463769868016243, 0.8462896943092346]
['동아일보', 0.04463769868016243]
[0.05488225817680359, 0.5947262644767761]
['새해', 0.05488225817

[0.0036132538225501776, 0.16030320525169373]
['염', 0.0036132538225501776]
[0.024543799459934235, -0.093739815056324]
['측정', 0.024543799459934235]
[-0.07942196726799011, 0.3351948857307434]
['불의', -0.07942196726799011]
[0.0072170584462583065, 0.06248293071985245]
['실험', 0.0072170584462583065]
[-0.12187237292528152, -0.0036900213453918695]
['무단', -0.12187237292528152]
[-0.017957640811800957, 0.12522511184215546]
['업주', -0.017957640811800957]
[0.4099658131599426, -0.015844304114580154]
['형사', 0.4099658131599426]
[-0.1768178790807724, 0.46553894877433777]
['정화', -0.1768178790807724]
[-0.0030090028885751963, 0.23205944895744324]
['정반대', -0.0030090028885751963]
[-0.07099089026451111, 0.4774387776851654]
['민간단체', -0.07099089026451111]
[-0.053268734365701675, 0.370018869638443]
['공추련', -0.053268734365701675]
[-0.030141556635499, 0.2615429759025574]
['문의', -0.030141556635499]
[-0.042529091238975525, 0.2843645215034485]
['빗발치', -0.042529091238975525]
[-0.09444493800401688, 0.6062586307525635]
['

['막무가내', -0.07674860209226608]
[0.33358773589134216, 0.391142874956131]
['수첩', 0.33358773589134216]
[0.13469170033931732, -0.016224097460508347]
['건네주', 0.13469170033931732]
[-0.07926316559314728, 0.2821541428565979]
['해달', -0.07926316559314728]
[0.08721475303173065, 0.033253226429224014]
['신변', 0.08721475303173065]
[0.05857325717806816, 0.12464404106140137]
['뿌리치', 0.05857325717806816]
[-0.13173002004623413, 0.28221049904823303]
['발길', -0.13173002004623413]
[-0.12680776417255402, 0.21863336861133575]
['반경', -0.12680776417255402]
[-0.055114638060331345, 0.39852744340896606]
['열심히', -0.055114638060331345]
[-0.11087284237146378, 0.5237010717391968]
['탈당', -0.11087284237146378]
[-0.12480513006448746, 0.38769474625587463]
['이철', -0.12480513006448746]
[0.050497911870479584, 0.058258626610040665]
['사퇴', 0.050497911870479584]
[0.018916072323918343, 0.3498624861240387]
['몸담', 0.018916072323918343]
[0.044382303953170776, 0.3339407444000244]
['초월', 0.044382303953170776]
[0.15115369856357574, 0.2

[0.00956906657665968, 0.3143679201602936]
['네', 0.00956906657665968]
[0.12024029344320297, 0.06623910367488861]
['설사', 0.12024029344320297]
[-0.023737434297800064, 0.3017231523990631]
['주도권', -0.023737434297800064]
[-0.10836230963468552, 0.654595136642456]
['변혁', -0.10836230963468552]
[-0.053285837173461914, 0.41325992345809937]
['자성', -0.053285837173461914]
[-0.2788727581501007, 0.415840744972229]
['합세', -0.2788727581501007]
[0.016165828332304955, 0.1663133203983307]
['절대적', 0.016165828332304955]
[0.018536483868956566, 0.29195359349250793]
['총동원', 0.018536483868956566]
[0.047856200486421585, 0.4451780319213867]
['침략', 0.047856200486421585]
[0.048219211399555206, 0.023719588294625282]
['가혹', 0.048219211399555206]
[-0.22873608767986298, 0.2563633322715759]
['뒤따르', -0.22873608767986298]
[0.01141938753426075, 0.300727516412735]
['중동전', 0.01141938753426075]
[0.10310795903205872, 0.18864494562149048]
['시나리오', 0.10310795903205872]
[0.014964648522436619, 0.16351933777332306]
['재현', 0.01496464

[0.008279804140329361, 0.20725859701633453]
['흔하', 0.008279804140329361]
[-0.07472345232963562, 0.5541499853134155]
['대자보', -0.07472345232963562]
[-0.08396486192941666, 0.286784827709198]
['나부끼', -0.08396486192941666]
[-0.09817429631948471, 0.2003883719444275]
['꺼내', -0.09817429631948471]
[-0.008813791908323765, 0.29134276509284973]
['거울', -0.008813791908323765]
[0.10342048853635788, 0.28151342272758484]
['소란', 0.10342048853635788]
[-0.03256028890609741, 0.3389613628387451]
['투영', -0.03256028890609741]
[-0.04791054502129555, 0.4080415368080139]
['가열', -0.04791054502129555]
[-0.04235495626926422, 0.32638612389564514]
['진로', -0.04235495626926422]
[-0.04754230007529259, 0.3146483898162842]
['들고나', -0.04754230007529259]
[0.029671521857380867, 0.29295238852500916]
['횡행', 0.029671521857380867]
[-0.07392676174640656, 0.2592603862285614]
['대학인', -0.07392676174640656]
[0.01021773274987936, 0.20015326142311096]
['부끄럽', 0.01021773274987936]
[0.03761901333928108, 0.19909271597862244]
['행하', 0.0376

[-0.010736833326518536, -0.13209891319274902]
['서류', -0.010736833326518536]
[-0.011051042936742306, 0.2072765827178955]
['강탈', -0.011051042936742306]
[0.21720166504383087, -0.05216946080327034]
['내사', 0.21720166504383087]
[0.1809522807598114, 0.1934601217508316]
['복역', 0.1809522807598114]
[-0.07755331695079803, 0.23365084826946259]
['정전', -0.07755331695079803]
[0.043583475053310394, 0.12377236038446426]
['수사본부', 0.043583475053310394]
[-0.2503329813480377, 0.39412274956703186]
['이장', -0.2503329813480377]
[0.06159191578626633, 0.31143224239349365]
['청원', 0.06159191578626633]
[-0.05280005931854248, 0.33799833059310913]
['유권해석', -0.05280005931854248]
[0.23183050751686096, 0.2180187851190567]
['비서', 0.23183050751686096]
[-0.0055642398074269295, 0.2733646333217621]
['서글프', -0.0055642398074269295]
[-0.1351085901260376, 0.5137963891029358]
['묘지', -0.1351085901260376]
[-0.028035668656229973, 0.190318301320076]
['바지', -0.028035668656229973]
[-0.006929648574441671, 0.22507944703102112]
['고모', -0.

[0.09980393201112747, 0.1931762993335724]
['고구려', 0.09980393201112747]
[-0.011657972820103168, 0.3063492774963379]
['머무르', -0.011657972820103168]
[-0.03869319334626198, 0.21602538228034973]
['정당화', -0.03869319334626198]
[-0.3857681155204773, 0.2697931230068207]
['대우자동차', -0.3857681155204773]
[-0.268250435590744, 0.2781701683998108]
['부평공장', -0.268250435590744]
[-0.18150611221790314, 0.8081334233283997]
['노동운', -0.18150611221790314]
[-0.15347863733768463, 0.48887425661087036]
['선도', -0.15347863733768463]
[-0.22832176089286804, 0.41735827922821045]
['거제', -0.22832176089286804]
[0.17131444811820984, 0.3250945508480072]
['조종', 0.17131444811820984]
[0.07637351006269455, 0.05461619421839714]
['업무방해', 0.07637351006269455]
[0.13902907073497772, 0.16878171265125275]
['입건', 0.13902907073497772]
[-0.0861322358250618, 0.30848434567451477]
['이면', -0.0861322358250618]
[0.05394648760557175, 0.3247728645801544]
['몇몇', 0.05394648760557175]
[-0.05129768326878548, 0.26793617010116577]
['이끌리', -0.05129768

[-0.030035842210054398, 0.3285614252090454]
['검약', -0.030035842210054398]
[-0.2240859419107437, 0.4984191060066223]
['새마을', -0.2240859419107437]
[-0.08747440576553345, 0.3639053702354431]
['실은', -0.08747440576553345]
[-0.24308834969997406, 0.3419358730316162]
['혼잡', -0.24308834969997406]
[-0.07071003317832947, 0.41540592908859253]
['물가고', -0.07071003317832947]
[-0.047693848609924316, 0.3922237455844879]
['찌들', -0.047693848609924316]
[-0.029541505500674248, 0.20160222053527832]
['핵미사일', -0.029541505500674248]
[0.09802079945802689, 0.1459439992904663]
['더하', 0.09802079945802689]
[-0.053965888917446136, 0.33777502179145813]
['핵전쟁', -0.053965888917446136]
[-0.00488382438197732, 0.3371830880641937]
['불확실', -0.00488382438197732]
[0.030114540830254555, 0.29258373379707336]
['획득', 0.030114540830254555]
[0.01498127356171608, 0.22214311361312866]
['그러하', 0.01498127356171608]
[-0.002862220164388418, 0.16249613463878632]
['천명하', -0.002862220164388418]
[0.020536955446004868, 0.18058684468269348]
['

[0.3224758803844452, 0.11848914623260498]
['공소사실', 0.3224758803844452]
[-0.028164876624941826, 0.28256264328956604]
['홀', -0.028164876624941826]
[0.18104420602321625, 0.1198628842830658]
['방배동', 0.18104420602321625]
[0.22361715137958527, 0.1706763654947281]
['서초동', 0.22361715137958527]
[0.1443079262971878, 0.21067139506340027]
['속초시', 0.1443079262971878]
[0.021716846153140068, 0.34291112422943115]
['청량리', 0.021716846153140068]
[0.3813232183456421, -0.05838721990585327]
['사칭', 0.3813232183456421]
[-0.22217553853988647, 0.28601929545402527]
['전동차', -0.22217553853988647]
[0.0794210284948349, 0.04763931781053543]
['일병', 0.0794210284948349]
[-0.06812813133001328, 0.07633135467767715]
['증명서', -0.06812813133001328]
[-0.04879426211118698, 0.3699255883693695]
['기호', -0.04879426211118698]
[-0.024038447067141533, 0.22359420359134674]
['면도기', -0.024038447067141533]
[-0.01750282756984234, 0.24445684254169464]
['종이컵', -0.01750282756984234]
[-0.05878758430480957, 0.13394026458263397]
['비누', -0.058787

[0.06602900475263596, 0.2642514407634735]
['금강산', 0.06602900475263596]
[-0.09213825315237045, 0.11511906236410141]
['구더기', -0.09213825315237045]
[0.06586184352636337, 0.4249352216720581]
['안성', 0.06586184352636337]
[-0.38465845584869385, 0.34055429697036743]
['전량', -0.38465845584869385]
[-0.09797268360853195, 0.20370200276374817]
['병무청', -0.09797268360853195]
[-0.09331946074962616, 0.24785944819450378]
['대성', -0.09331946074962616]
[0.01714424043893814, 0.36626026034355164]
['열풍', 0.01714424043893814]
[-0.047649260610342026, 0.36121666431427]
['교육행정', -0.047649260610342026]
[-0.12770429253578186, 0.40177983045578003]
['평준', -0.12770429253578186]
[0.0860242024064064, 0.12618587911128998]
['착복', 0.0860242024064064]
[0.022579355165362358, 0.23621898889541626]
['컨테이너', 0.022579355165362358]
[0.37569090723991394, -0.20272138714790344]
['불하', 0.37569090723991394]
[0.13222083449363708, 0.15191568434238434]
['입학자', 0.13222083449363708]
[-0.22750785946846008, 0.3926998972892761]
['스텔라', -0.22750

['후광', 0.24424949288368225]
[0.13949371874332428, 0.17543944716453552]
['후광효과', 0.13949371874332428]
[0.015957225114107132, 0.2819105088710785]
['판서', 0.015957225114107132]
[0.013554142788052559, 0.24116526544094086]
['나열', 0.013554142788052559]
[-0.057899631559848785, 0.3235703110694885]
['공연히', -0.057899631559848785]
[0.1411695033311844, 0.2909562289714813]
['김달현', 0.1411695033311844]
[-0.01632660999894142, 0.30720895528793335]
['경색', -0.01632660999894142]
[0.01774892956018448, 0.2637614905834198]
['풍요', 0.01774892956018448]
[0.017543166875839233, 0.27970167994499207]
['궁택', 0.017543166875839233]
[-0.017748277634382248, 0.30497846007347107]
['팡', -0.017748277634382248]
[0.07074286043643951, 0.37092307209968567]
['혁명가', 0.07074286043643951]
[0.06590371578931808, 0.2769557237625122]
['정치헌금', 0.06590371578931808]
[-0.038477350026369095, 0.5475066900253296]
['공화', -0.038477350026369095]
[0.0794517919421196, 0.3329617381095886]
['카스트로', 0.0794517919421196]
[-0.06730269640684128, 0.2760340

In [12]:
model = Word2Vec.load('embedding_window10_mincnt5_skipgram.model1')

print('===================')
similarWords = model.wv.most_similar(positive = ['행복', '웃음', '밝'], topn =3)
print(similarWords)
#positive와 유사한 단어들을 3개 추출 

[('깜짝', 0.9777832627296448), ('숙연', 0.9659484028816223), ('끊어지', 0.9651718139648438)]


In [13]:
word = []
for similarWord in similarWords:
    word.append(similarWord[0])
print(word)
#임베딩값은 추출하지않고 word라는 빈 리스트에 형태소가 분석된 단어들만 추가 

['깜짝', '숙연', '끊어지']


### 네이버 뉴스 샘플

In [15]:
import os 
naver_dir = '/Users/Moon/Desktop/Summer/NLP/pytest/네이버뉴스-생활문화_다중/'
train_dir = os.path.join(naver_dir, 'train')
test_dir = os.path.join(naver_dir, 'test')

label_types = ['건강정보', '공연전시', '도로교통', '여행레저', '음식맛집', '자동차시승기', '종교', '책', '패션뷰티']
#os패키지를 이용하여 디렉토리를 지정 

In [29]:
train_dir

'/Users/Moon/Desktop/Summer/NLP/pytest/네이버뉴스-생활문화_다중/train'

In [30]:
def make_texts_labels(dir, label_types, encode = 'utf-8'):
    texts =[]
    labels = []
    #각각 빈리스트를 만든다
    
    for label_type in label_types:
        dir_name = os.path.join(dir, label_type) 
        #각각의 라벨폴더에 접근
        for fname in os.listdir(dir_name):
            if fname[-4:] == '.txt': #끝에서부터 4번째까지가 .txt일때 
                f = open(os.path.join(dir_name,fname), encoding = encode)
                texts.append(f.read())
                f.close()
                
                if label_type == label_types[0]: #label_types[0]이 저장되어있는 것과 같을때 
                    labels.append(0)
                elif label_type == label_types[1]:
                    labels.append(1)
                elif label_type == label_types[2]:
                    labels.append(2)
                elif label_type == label_types[3]:
                    labels.append(3)
                elif label_type == label_types[4]:
                    labels.append(4)
                elif label_type == label_types[5]:
                    labels.append(5)
                elif label_type == label_types[6]:
                    labels.append(6)
                elif label_type == label_types[7]:
                    labels.append(7)
                elif label_type == label_types[8]:
                    labels.append(8)
    return texts,labels
#os패키지에 대해 이해가 부족함
#특정 폴더에 있는 데이터를 불러와서 빈리스트에 저장하고 해당 폴더의 이름을 확인하여 labels리스트에 분류를 적는 함수를 만듬 

In [31]:
texts, labels = make_texts_labels(train_dir, label_types)

print(texts[0])
print(len(texts))
print(labels[0])
print(len(labels))

SK케미칼, 백신 사업 분사 결정 : 네이버 뉴스







글로벌화 단계 진입…올해 백신사업 분사로 별도법인 설립SK케미칼이 주력 사업부문인 백신 사업을 별도 법인으로 분리한다.SK케미칼은 글로벌 프리미엄 백신 회사로 도약을 위해 올해 안에 백신 사업을 분사할 예정이라고 12일 공시했다.SK케미칼은 2006년부터 백신을 미래 성장 동력으로 육성하기 위해 인프라구축에 약 4000억원을 투자했다. 지난 2012년에는 경북 안동에 세포배양 백신 등 차세대 백신을 생산할 수 있는 백신공장 'L하우스'를 짓고 독감백신, 대상포진백신 등을 생산했다. SK케미칼의 사업 부문별 비중을 보면 합성의약품은 약 60%, 백신은 40% 규모다.SK케미칼은 앞으로 분사한 별도법인에 대한 SI(전략적투자자)를 본격적으로 유치하고 기업공개(IPO)를 통해 주주가치 제고에 기여하겠다는 계획이다.SK케미칼 측은 "지속적인 노력의 성과로 사노피 파스퇴르와 차세대폐렴구균 공동개발 계약 체결, 세포배양방식의 독감백신 3·4가 및 대상포진 백신 출시 등 다양한 성과를 창출해 왔다"며 "자체 기술 경쟁력을 바탕으로 글로벌화의 본격화 단계에 진입했다"고 밝혔다.김지섭기자 cloud50@dt.co.kr 디지털타임스 홈페이지 바로가기 / SNS 바로가기디지털타임스 영문뉴스 바로가기 / 카드뉴스 바로가기김지섭
	

90
0
90


In [32]:
texts = [rhinoMorph.onlyMorph_list(rn, sentence, pos= ['NNG', 'NNP','NP', 'VV', 'VA', 'XR', 'IC', 'MM', 'MAG', 'MAJ'], eomi = False) for sentence in texts]
#texts를 sentence라는 반복문으로돌리고 해당 반복문에서 생성된 객체를 형태소분석을 진행해서 다시 texts로 저장 
print(texts[0])

['SK', '케미칼', '백신', '사업', '분사', '결정', '네이버', '뉴스', '글로벌', '단계', '진입', '올해', '백신', '사업', '분사', '별도', '법인', '설립', 'SK', '케미칼', '주력', '사업', '부문', '백신', '사업', '별도', '법인', '분리', 'SK', '케미칼', '글로벌', '프리미엄', '백신', '회사', '도약', '위하', '올해', '안', '백신', '사업', '분사', '예정', '공시', 'SK', '케미칼', '백신', '미래', '성장', '동력', '육성', '위하', '인프라', '구축', '약', '투자', '지나', '경북', '안동', '세포', '배양', '백신', '차세대', '백신', '생산', '백신', '공장', '하우스', '짓', '독감', '백신', '대상포진', '백신', '등', '생산', 'SK', '케미칼', '사업', '부문', '비중', '합성', '의약품', '약', '백신', '규모', 'SK', '케미칼', '앞', '분사', '하', '별도', '법인', '대하', '전략적', '투자자', '본격적', '유치', '기업공개', '통하', '주주', '가치', '제고', '기여', '계획', 'SK', '케미칼', '지속적', '노력', '성과', '사노', '피', '파스퇴르', '차세대', '폐렴', '구균', '공동', '개발', '계약', '체결', '세포', '배양', '방식', '독감', '백신', '가', '및', '대상포진', '백신', '출시', '다양', '하', '성과', '창출', '자체', '기술', '경쟁력', '바탕', '글로벌', '본격화', '단계', '진입', '밝히', '김지섭', '디지털', '타임스', '홈페이지', '바로', '가', 'SNS', '바로', '가', '디지털', '타임스', '영문', '뉴스', '바로', '가', '카드', '뉴스', '바로', '가', '김', '지섭']


In [33]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import math

In [34]:
validation_ratio = math.floor(len(texts) * 0.3)
max_words = 10000
maxlen = 200
class_number = 9

In [36]:
tokenizer = Tokenizer(num_words = max_words)
#max_words로 지정한만큼 토큰화 
tokenizer.fit_on_texts(texts)
#texts를 토큰화해줌 
word_index = tokenizer.word_index
#word_index는 토큰화한것에 대한 각 단어의 인덱스를 저장 

In [40]:
print('전체 %s개의 고유한 토큰을 찾았습니다.' %len(word_index))
print(word_index)

전체 5351개의 고유한 토큰을 찾았습니다.
{'하': 1, '되': 2, '있': 3, '뉴스': 4, '네이버': 5, '및': 6, '이': 7, '기자': 8, '그': 9, '위하': 10, '한국': 11, '시간': 12, '서울': 13, '보': 14, '가': 15, '받': 16, '배포': 17, '대하': 18, '무단': 19, '전재': 20, '제공': 21, '김': 22, '주': 23, '금지': 24, '고객': 25, '통하': 26, '올림픽': 27, '평창': 28, '설': 29, '바로': 30, '제품': 31, '작품': 32, '제보': 33, '없': 34, '스포츠서울': 35, '발생': 36, '작가': 37, '밝히': 38, '다양': 39, '서비스': 40, '사진': 41, '자궁': 42, '이상': 43, '가장': 44, '시장': 45, '사람': 46, '계획': 47, '때': 48, '말하': 49, '정부': 50, '대표': 51, '책': 52, '진행': 53, '관련': 54, '사업': 55, '따르': 56, '한경': 57, '컬러': 58, '약': 59, '경우': 60, '수': 61, '지역': 62, '이번': 63, '오': 64, '위': 65, '크': 66, '공식': 67, '나': 68, '연휴': 69, '가격': 70, '속': 71, '지난해': 72, '교수': 73, '해외': 74, '공연': 75, '등': 76, '한': 77, '함께': 78, '지원': 79, '핑크': 80, '채널': 81, '김지현': 82, '도로': 83, '차량': 84, '문제': 85, '국가': 86, '시': 87, '안전': 88, '사량': 89, '많': 90, '기간': 91, '만들': 92, '녹': 93, '여성': 94, '연구': 95, '결과': 96, '더': 97, '같': 98, '말': 99, '알': 100, '국내':

In [45]:
data = tokenizer.texts_to_sequences(texts)
#각 단어 인덱스를 숫자 리스트로 변환해줌 
print(len(data))
#전체 데이터셋이 90개임으로 잘된것을 확인 

90


In [49]:
data = pad_sequences(data, maxlen = maxlen)
print(data)
print(data[0])
#한 리스트당 길이를 200개로 지정을 해줌 

[[   0    0    0 ...   15   22 1094]
 [ 456  451 1894 ...    6   17   24]
 [   0    0    0 ...   15   22 1094]
 ...
 [  16  120   10 ...    6   17   24]
 [   0    0    0 ...  167  573  574]
 [   0    0    0 ...   33  537   35]]
[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0  443  600  221   55
 1081  256    5    4  257  865 1082  276  221   55 1081  722 1083  866
  443  600 1369   55  444  221   55  722 1083 2785  443  600  257 1084
  221  222 1858   10  276  159  221   55 1081  344 2786  443  600  221
  867  223 2787 2788   10 1370  345   59  314  107 1085 1859 1860 1861
  221 1862  221  174  221  868  388 1086 1863  221 1864  221   76  174
  443  600   55  444  869 2789  510   59  221  346  443  600  195 1081
    1  722 1083   18 1865 1866 1371 1087 2790   26 1088 1089 2791 1090
   47  443  600 2792  347 1091 2793  175 2794 1862 2795 2796  

In [60]:
import numpy as np

In [67]:
def to_one_hot(labels, dimension):
    results = np.zeros((len(labels), dimension))
    #0행렬을 만듬 
    for i,label in enumerate(labels):
        results[i,label] = 1.
    return results
#위의 매개함수의 뜻은 label이 0이면 i가 label의 길이만큼 증가하고 이후 label이 1이 되는 과정을 계속 반복 

In [68]:
labels = to_one_hot(labels, dimension = class_number)
#잘못누름 labels에 저장됨

IndexError: arrays used as indices must be of integer (or boolean) type

In [69]:
labels
#정확하게 출력이 되는 것을 확인을 할 수 있음
#한 리스트의 값을 전부 더하면 1이 되는 softmax함수를 사용
#softmax함수는 output이 확률의 형태로 나타나며 전부 더했을때 1이됨

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0.

In [71]:
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
data = data[indices]
labels = labels[indices]
#아마 섞어주는 역활일거임 
#나중에 다시 보기!!😊

In [72]:
X_train = data[validation_ratio:]
y_train = data[validation_ratio:]
X_test = data[:validation_ratio]
y_test = data[:validation_ratio]
#validation_ratio를 기준으로 train과 test셋을 자름 

In [74]:
filepath

'/Users/Moon/Desktop/Summer/NLP/pytest/'

In [76]:
embeddings_index = {}
f = open(os.path.join(filepath + 'word2vec', 'embedding_window10_mincnt5_skipgram.txt'),
        encoding = 'utf-8')
for line in f:
    values = line.split()#행을 분리
    word = values[0]#단어는 value의 첫번쨰에 존재 
    coefs = np.asarray(values[1:], dtype = 'float32')#첫번쨰이후부터는 임베딩값만 존재 
    embeddings_index[word]= coefs
f.close()

In [99]:
embedding_matrix = np.zeros((max_words, embedding_dim))
#0으로 채워진 빈행렬을 만듬 
for word, i in word_index.items():
    if i < max_words:
        embedding_vector = embeddings_index.get(word) #해당 단어의 벡터를 가져옴 
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector 
#이부분 이해가 안감 
#다시 보기

In [100]:
from tensorflow.keras import models
from tensorflow.keras import layers

In [101]:
model = models.Sequential()#모델 생성 
model.add(layers.Embedding(input_dim = max_words, output_dim = embedding_dim, input_length = maxlen))
#인풋은 10000개 output은 50개 각 input의 길이는 200
model.add(layers.Flatten())
model.add(layers.Dense(units =32 , activation = 'relu'))
model.add(layers.Dense(units = class_number, activation = 'softmax'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 200, 50)           500000    
_________________________________________________________________
flatten_2 (Flatten)          (None, 10000)             0         
_________________________________________________________________
dense_2 (Dense)              (None, 32)                320032    
_________________________________________________________________
dense_3 (Dense)              (None, 9)                 297       
Total params: 820,329
Trainable params: 820,329
Non-trainable params: 0
_________________________________________________________________


In [102]:
model.layers[0].set_weights([embedding_matrix])
model.layers[0].trinable = False
#layers[0]에는 단어라서 학습이 안되게 하는건가???....
#이까지가 keras 임베딩의 과정 

In [103]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])

In [105]:
history = model.fit(X_train, y_train, epochs = 10, batch_size = 64)
history_dict = history.history

ValueError: A target array with shape (63, 200) was passed for an output of shape (None, 9) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.