In [1]:
import rhinoMorph
from nltk.tokenize import sent_tokenize
import nltk
rn = rhinoMorph.startRhino()

filepath:  /Users/Moon/opt/anaconda3/lib/python3.7/site-packages
classpath:  /Users/Moon/opt/anaconda3/lib/python3.7/site-packages/rhinoMorph/lib/rhino.jar
RHINO started!


In [2]:
import os 
naver_dir = '/Users/Moon/Desktop/Summer/NLP/pytest/네이버뉴스-생활문화_다중/'
train_dir = os.path.join(naver_dir, 'train')
test_dir = os.path.join(naver_dir, 'test')

label_types = ['건강정보', '공연전시', '도로교통', '여행레저', '음식맛집', '자동차시승기', '종교', '책', '패션뷰티']
#os패키지를 이용하여 디렉토리를 지정 

In [3]:
def make_texts_labels(dir, label_types, encode = 'utf-8'):
    texts =[]
    labels = []
    #각각 빈리스트를 만든다
    
    for label_type in label_types:
        dir_name = os.path.join(dir, label_type) 
        #각각의 라벨폴더에 접근
        for fname in os.listdir(dir_name):
            if fname[-4:] == '.txt': #끝에서부터 4번째까지가 .txt일때 
                f = open(os.path.join(dir_name,fname), encoding = encode)
                texts.append(f.read())
                f.close()
                
                if label_type == label_types[0]: #label_types[0]이 저장되어있는 것과 같을때 
                    labels.append(0)
                elif label_type == label_types[1]:
                    labels.append(1)
                elif label_type == label_types[2]:
                    labels.append(2)
                elif label_type == label_types[3]:
                    labels.append(3)
                elif label_type == label_types[4]:
                    labels.append(4)
                elif label_type == label_types[5]:
                    labels.append(5)
                elif label_type == label_types[6]:
                    labels.append(6)
                elif label_type == label_types[7]:
                    labels.append(7)
                elif label_type == label_types[8]:
                    labels.append(8)
    return texts,labels
#os패키지에 대해 이해가 부족함
#특정 폴더에 있는 데이터를 불러와서 빈리스트에 저장하고 해당 폴더의 이름을 확인하여 labels리스트에 분류를 적는 함수를 만듬 

In [4]:
texts, labels = make_texts_labels(train_dir, label_types)

print(texts[0])
print(len(texts))
print(labels[0])
print(len(labels))

SK케미칼, 백신 사업 분사 결정 : 네이버 뉴스







글로벌화 단계 진입…올해 백신사업 분사로 별도법인 설립SK케미칼이 주력 사업부문인 백신 사업을 별도 법인으로 분리한다.SK케미칼은 글로벌 프리미엄 백신 회사로 도약을 위해 올해 안에 백신 사업을 분사할 예정이라고 12일 공시했다.SK케미칼은 2006년부터 백신을 미래 성장 동력으로 육성하기 위해 인프라구축에 약 4000억원을 투자했다. 지난 2012년에는 경북 안동에 세포배양 백신 등 차세대 백신을 생산할 수 있는 백신공장 'L하우스'를 짓고 독감백신, 대상포진백신 등을 생산했다. SK케미칼의 사업 부문별 비중을 보면 합성의약품은 약 60%, 백신은 40% 규모다.SK케미칼은 앞으로 분사한 별도법인에 대한 SI(전략적투자자)를 본격적으로 유치하고 기업공개(IPO)를 통해 주주가치 제고에 기여하겠다는 계획이다.SK케미칼 측은 "지속적인 노력의 성과로 사노피 파스퇴르와 차세대폐렴구균 공동개발 계약 체결, 세포배양방식의 독감백신 3·4가 및 대상포진 백신 출시 등 다양한 성과를 창출해 왔다"며 "자체 기술 경쟁력을 바탕으로 글로벌화의 본격화 단계에 진입했다"고 밝혔다.김지섭기자 cloud50@dt.co.kr 디지털타임스 홈페이지 바로가기 / SNS 바로가기디지털타임스 영문뉴스 바로가기 / 카드뉴스 바로가기김지섭
	

90
0
90


In [5]:
texts = [rhinoMorph.onlyMorph_list(rn, sentence, pos= ['NNG', 'NNP','NP', 'VV', 'VA', 'XR', 'IC', 'MM', 'MAG', 'MAJ'], eomi = False) for sentence in texts]
#texts를 sentence라는 반복문으로돌리고 해당 반복문에서 생성된 객체를 형태소분석을 진행해서 다시 texts로 저장 
print(texts[0])

['SK', '케미칼', '백신', '사업', '분사', '결정', '네이버', '뉴스', '글로벌', '단계', '진입', '올해', '백신', '사업', '분사', '별도', '법인', '설립', 'SK', '케미칼', '주력', '사업', '부문', '백신', '사업', '별도', '법인', '분리', 'SK', '케미칼', '글로벌', '프리미엄', '백신', '회사', '도약', '위하', '올해', '안', '백신', '사업', '분사', '예정', '공시', 'SK', '케미칼', '백신', '미래', '성장', '동력', '육성', '위하', '인프라', '구축', '약', '투자', '지나', '경북', '안동', '세포', '배양', '백신', '차세대', '백신', '생산', '백신', '공장', '하우스', '짓', '독감', '백신', '대상포진', '백신', '등', '생산', 'SK', '케미칼', '사업', '부문', '비중', '합성', '의약품', '약', '백신', '규모', 'SK', '케미칼', '앞', '분사', '하', '별도', '법인', '대하', '전략적', '투자자', '본격적', '유치', '기업공개', '통하', '주주', '가치', '제고', '기여', '계획', 'SK', '케미칼', '지속적', '노력', '성과', '사노', '피', '파스퇴르', '차세대', '폐렴', '구균', '공동', '개발', '계약', '체결', '세포', '배양', '방식', '독감', '백신', '가', '및', '대상포진', '백신', '출시', '다양', '하', '성과', '창출', '자체', '기술', '경쟁력', '바탕', '글로벌', '본격화', '단계', '진입', '밝히', '김지섭', '디지털', '타임스', '홈페이지', '바로', '가', 'SNS', '바로', '가', '디지털', '타임스', '영문', '뉴스', '바로', '가', '카드', '뉴스', '바로', '가', '김', '지섭']


In [6]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import math

In [7]:
validation_ratio = math.floor(len(texts) * 0.3)
#validation비율을 나타냄 
max_words = 10000
#최대 단어를 만개
maxlen = 200
#문장의 최대 길이를 200
class_number = 9

tokenizer = Tokenizer(num_words = max_words)
#max_words로 지정한만큼 토큰화 
tokenizer.fit_on_texts(texts)
#texts를 토큰화해줌 
word_index = tokenizer.word_index
#word_index는 토큰화한것에 대한 각 단어의 인덱스를 저장 
#10000개의 토큰화한 것들에 대해 각각의 고유한 인덱스 번호를 지정 
#인덱스 번호 부여 기준은 빈도가 높은 순서대로 부여 

In [8]:
data = tokenizer.texts_to_sequences(texts)
#각 단어 인덱스를 숫자 리스트로 변환해줌 
print(data)
#전체 데이터셋이 90개이고 각 기사마다 토큰화한것들에 대해 고유한 인덱스가 부여된것을 확인 

[[443, 600, 221, 55, 1081, 256, 5, 4, 257, 865, 1082, 276, 221, 55, 1081, 722, 1083, 866, 443, 600, 1369, 55, 444, 221, 55, 722, 1083, 2785, 443, 600, 257, 1084, 221, 222, 1858, 10, 276, 159, 221, 55, 1081, 344, 2786, 443, 600, 221, 867, 223, 2787, 2788, 10, 1370, 345, 59, 314, 107, 1085, 1859, 1860, 1861, 221, 1862, 221, 174, 221, 868, 388, 1086, 1863, 221, 1864, 221, 76, 174, 443, 600, 55, 444, 869, 2789, 510, 59, 221, 346, 443, 600, 195, 1081, 1, 722, 1083, 18, 1865, 1866, 1371, 1087, 2790, 26, 1088, 1089, 2791, 1090, 47, 443, 600, 2792, 347, 1091, 2793, 175, 2794, 1862, 2795, 2796, 348, 128, 511, 1867, 1860, 1861, 601, 1863, 221, 15, 6, 1864, 221, 196, 39, 1, 1091, 1372, 602, 512, 603, 723, 257, 1092, 865, 1082, 38, 1093, 197, 389, 129, 30, 15, 198, 30, 15, 197, 389, 870, 4, 30, 15, 315, 4, 30, 15, 22, 1094], [42, 724, 277, 94, 1095, 224, 5, 4, 130, 108, 144, 2, 1373, 95, 96, 42, 131, 16, 1374, 725, 199, 1375, 2, 1868, 109, 14, 2, 2797, 513, 1096, 42, 131, 85, 1376, 2798, 445, 1377

In [9]:
data = pad_sequences(data, maxlen = maxlen)
print(data)
#한 리스트당 길이를 200개로 지정을 해줌 
#지정을 하지 않으면 학습이 되지 않거나 좋지 못한 결과가 나옴 
#만약 200개가 안된다면 앞에 0을 넣어주는 Padding을 사용 

[[   0    0    0 ...   15   22 1094]
 [ 456  451 1894 ...    6   17   24]
 [   0    0    0 ...   15   22 1094]
 ...
 [  16  120   10 ...    6   17   24]
 [   0    0    0 ...  167  573  574]
 [   0    0    0 ...   33  537   35]]


In [10]:
import numpy as np

def to_one_hot(labels, dimension):
    results = np.zeros((len(labels), dimension))
    #0행렬을 만듬 
    for i,label in enumerate(labels):
        results[i,label] = 1.
    return results
#위의 매개함수의 뜻은 label이 0이면 i가 label의 길이만큼 증가하고 이후 label이 1이 되는 과정을 계속 반복  

In [11]:
labels = to_one_hot(labels, dimension = class_number)

In [12]:
labels
#각 값마다 라벨값을 부여 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0.

In [13]:
indices = np.arange(data.shape[0])
print(indices)
np.random.shuffle(indices)
print(indices)
#랜덤하게 섞어줌 
data = data[indices]
labels = labels[indices]
#이렇게 랜덤하게 섞어주어 모델의 신뢰성을 높임 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
[77 80 26 68 25 28 62 30 81 83  6 65 72 44 43 73 36 34 47 10 40 61 79 38
  8 16 86 45 29 23  7  1  4 63 88 85 32 24 74 59 20 37  9  3 87 17 64 53
 89 69 35 70 67 56 82 33 12 39 54  2 76 31 21 52 66 48 41 27 57 84 78 42
  0 22 75 15 55 13 46 51 49 11 50 58 18 19 14 71 60  5]


In [14]:
X_train = data[validation_ratio:]
y_train = labels[validation_ratio:]
X_test = data[:validation_ratio]
y_test = labels[:validation_ratio]

In [15]:
from tensorflow.keras import models
from tensorflow.keras import layers
from keras.layers import Activation, SimpleRNN

Using TensorFlow backend.


In [17]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
#input node가 만개, output이 50개 각 노드의 길이는 200
model.add(layers.SimpleRNN(50))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 50)           500000    
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 50)                5050      
_________________________________________________________________
dense_1 (Dense)              (None, 30)                1530      
_________________________________________________________________
dense_2 (Dense)              (None, 9)                 279       
Total params: 506,859
Trainable params: 506,859
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])

In [19]:
print(X_train.shape)
print(y_train.shape)

(63, 200)
(63, 9)


In [20]:
model.fit(X_train, y_train,  epochs = 200, batch_size = 64)
#거의 과적합이고 데이터의 개수가 부족하여 validation을 나누지 못함

Train on 63 samples
Epoch 1/200
63/63 [==============================] - 2s 25ms/sample - loss: 2.2130 - acc: 0.1111
Epoch 2/200
63/63 [==============================] - 0s 1ms/sample - loss: 1.9464 - acc: 0.6667
Epoch 3/200
63/63 [==============================] - 0s 976us/sample - loss: 1.8575 - acc: 0.6508
Epoch 4/200
63/63 [==============================] - 0s 1ms/sample - loss: 1.6991 - acc: 0.8730
Epoch 5/200
63/63 [==============================] - 0s 1ms/sample - loss: 1.5918 - acc: 0.8730
Epoch 6/200
63/63 [==============================] - 0s 988us/sample - loss: 1.4540 - acc: 0.9841
Epoch 7/200
63/63 [==============================] - 0s 1ms/sample - loss: 1.3328 - acc: 0.9841
Epoch 8/200
63/63 [==============================] - 0s 995us/sample - loss: 1.2407 - acc: 1.0000
Epoch 9/200
63/63 [==============================] - 0s 1ms/sample - loss: 1.1355 - acc: 1.0000
Epoch 10/200
63/63 [==============================] - 0s 1ms/sample - loss: 1.0495 - acc: 1.0000
Epoch 11/200

In [21]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
#input node가 만개, output이 50개 각 노드의 길이는 200
model.add(layers.LSTM(50))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 200, 50)           500000    
_________________________________________________________________
lstm (LSTM)                  (None, 50)                20200     
_________________________________________________________________
dense_3 (Dense)              (None, 30)                1530      
_________________________________________________________________
dense_4 (Dense)              (None, 9)                 279       
Total params: 522,009
Trainable params: 522,009
Non-trainable params: 0
_________________________________________________________________


In [22]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 200, batch_size = 64)
#데이터의 개수가 부족하여 validation을 나누지 못함 
#신기한게 과거의 정보를 학습해서 그런지 모르겠지만 점점 acc가 높아짐 

Train on 63 samples
Epoch 1/200
63/63 [==============================] - 2s 35ms/sample - loss: 2.1968 - acc: 0.0794
Epoch 2/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1901 - acc: 0.1270
Epoch 3/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1817 - acc: 0.1746
Epoch 4/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1722 - acc: 0.1746
Epoch 5/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1601 - acc: 0.1905
Epoch 6/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1419 - acc: 0.2222
Epoch 7/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1108 - acc: 0.2222
Epoch 8/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.0056 - acc: 0.2063
Epoch 9/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.0639 - acc: 0.1429
Epoch 10/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.0133 - acc: 0.5079
Epoch 11/200
63/63

In [23]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
#input node가 만개, output이 50개 각 노드의 길이는 200
model.add(layers.GRU(50))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()
#다음에 노드를 엄청 복잡하게 쌓아봐야겠음 

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 200, 50)           500000    
_________________________________________________________________
gru (GRU)                    (None, 50)                15300     
_________________________________________________________________
dense_5 (Dense)              (None, 30)                1530      
_________________________________________________________________
dense_6 (Dense)              (None, 9)                 279       
Total params: 517,109
Trainable params: 517,109
Non-trainable params: 0
_________________________________________________________________


In [24]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 200, batch_size = 64)
#데이터의 개수가 부족하여 validation을 나누지 못함 
#LSTM에 비해 확실히 연산속도가 빠르고 acc가 꾸준하게 올라감 

Train on 63 samples
Epoch 1/200
63/63 [==============================] - 2s 33ms/sample - loss: 2.1977 - acc: 0.1111
Epoch 2/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1869 - acc: 0.1746
Epoch 3/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1766 - acc: 0.1746
Epoch 4/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1666 - acc: 0.2381
Epoch 5/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1563 - acc: 0.3175
Epoch 6/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1453 - acc: 0.3175
Epoch 7/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1334 - acc: 0.3651
Epoch 8/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1205 - acc: 0.3333
Epoch 9/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.1071 - acc: 0.3651
Epoch 10/200
63/63 [==============================] - 0s 2ms/sample - loss: 2.0917 - acc: 0.3651
Epoch 11/200
63/63

### 규제

In [26]:
from keras import regularizers

In [31]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
model.add(layers.LSTM(50))
model.add(layers.Dense(30, kernel_regularizer = regularizers.l1(0.001),activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_9 (Embedding)      (None, 200, 50)           500000    
_________________________________________________________________
lstm_3 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_7 (Dense)              (None, 30)                1530      
_________________________________________________________________
dense_8 (Dense)              (None, 9)                 279       
Total params: 522,009
Trainable params: 522,009
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 64)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 2s 33ms/sample - loss: 2.4034 - acc: 0.0794
Epoch 2/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.3906 - acc: 0.1587
Epoch 3/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.3795 - acc: 0.2063
Epoch 4/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.3668 - acc: 0.1587
Epoch 5/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.3482 - acc: 0.2540
Epoch 6/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.3090 - acc: 0.1746
Epoch 7/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1544 - acc: 0.3333
Epoch 8/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.0685 - acc: 0.3175
Epoch 9/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.0972 - acc: 0.3175
Epoch 10/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.7213 - acc: 0.2540
Epoch 11/100
63/63

In [33]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
#input node가 만개, output이 50개 각 노드의 길이는 200
model.add(layers.LSTM(50))
model.add(layers.Dense(30, kernel_regularizer = regularizers.l2(0.01),activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_10"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_10 (Embedding)     (None, 200, 50)           500000    
_________________________________________________________________
lstm_4 (LSTM)                (None, 50)                20200     
_________________________________________________________________
dense_9 (Dense)              (None, 30)                1530      
_________________________________________________________________
dense_10 (Dense)             (None, 9)                 279       
Total params: 522,009
Trainable params: 522,009
Non-trainable params: 0
_________________________________________________________________


In [34]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 64)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 2s 32ms/sample - loss: 2.5628 - acc: 0.1270
Epoch 2/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.5409 - acc: 0.0794
Epoch 3/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.5229 - acc: 0.3492
Epoch 4/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.5058 - acc: 0.2698
Epoch 5/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.4870 - acc: 0.2698
Epoch 6/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.4642 - acc: 0.2698
Epoch 7/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.4248 - acc: 0.2381
Epoch 8/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.5253 - acc: 0.1587
Epoch 9/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.4001 - acc: 0.4127
Epoch 10/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.3748 - acc: 0.3492
Epoch 11/100
63/63

In [69]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
#input node가 만개, output이 50개 각 노드의 길이는 200
model.add(layers.LSTM(50))
model.add(layers.Dense(30, kernel_regularizer = regularizers.l1_l2(l1 = 0.01, l2 = 0.001),activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_33"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_31 (Embedding)     (None, 200, 50)           500000    
_________________________________________________________________
lstm_24 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_24 (Dense)             (None, 30)                1530      
_________________________________________________________________
dense_25 (Dense)             (None, 9)                 279       
Total params: 522,009
Trainable params: 522,009
Non-trainable params: 0
_________________________________________________________________


In [70]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 64)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 2s 29ms/sample - loss: 4.3122 - acc: 0.1746
Epoch 2/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.2542 - acc: 0.3175
Epoch 3/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.2110 - acc: 0.2222
Epoch 4/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.1732 - acc: 0.2698
Epoch 5/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.1369 - acc: 0.2540
Epoch 6/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.1010 - acc: 0.2698
Epoch 7/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.0611 - acc: 0.2698
Epoch 8/100
63/63 [==============================] - 0s 2ms/sample - loss: 4.0126 - acc: 0.3492
Epoch 9/100
63/63 [==============================] - 0s 2ms/sample - loss: 3.9309 - acc: 0.2381
Epoch 10/100
63/63 [==============================] - 0s 2ms/sample - loss: 3.9283 - acc: 0.1587
Epoch 11/100
63/63

### Dropout

In [37]:
from keras.layers import Dropout

In [43]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
model.add(layers.LSTM(50, dropout= 0.3))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_18"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_18 (Embedding)     (None, 200, 50)           500000    
_________________________________________________________________
lstm_12 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_12 (Dense)             (None, 30)                1530      
_________________________________________________________________
dense_13 (Dense)             (None, 9)                 279       
Total params: 522,009
Trainable params: 522,009
Non-trainable params: 0
_________________________________________________________________


In [44]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 64)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 2s 34ms/sample - loss: 2.1953 - acc: 0.1429
Epoch 2/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1842 - acc: 0.2381
Epoch 3/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1743 - acc: 0.2540
Epoch 4/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1627 - acc: 0.2857
Epoch 5/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1471 - acc: 0.3175
Epoch 6/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1303 - acc: 0.3333
Epoch 7/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1043 - acc: 0.3175
Epoch 8/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.0681 - acc: 0.3651
Epoch 9/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.0038 - acc: 0.3810
Epoch 10/100
63/63 [==============================] - 0s 2ms/sample - loss: 1.8982 - acc: 0.3968
Epoch 11/100
63/63

In [47]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
model.add(layers.LSTM(50))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()
#dropout layer를 추가하고 성능이 좋지못함 

Model: "sequential_21"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_21 (Embedding)     (None, 200, 50)           500000    
_________________________________________________________________
lstm_15 (LSTM)               (None, 50)                20200     
_________________________________________________________________
dense_16 (Dense)             (None, 30)                1530      
_________________________________________________________________
dropout (Dropout)            (None, 30)                0         
_________________________________________________________________
dense_17 (Dense)             (None, 9)                 279       
Total params: 522,009
Trainable params: 522,009
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 64)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 2s 36ms/sample - loss: 2.2003 - acc: 0.0159
Epoch 2/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1923 - acc: 0.1587
Epoch 3/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1916 - acc: 0.2063
Epoch 4/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1859 - acc: 0.2063
Epoch 5/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1846 - acc: 0.2222
Epoch 6/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1752 - acc: 0.2540
Epoch 7/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1647 - acc: 0.3016
Epoch 8/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1549 - acc: 0.3016
Epoch 9/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.1446 - acc: 0.2857
Epoch 10/100
63/63 [==============================] - 0s 2ms/sample - loss: 2.0913 - acc: 0.1746
Epoch 11/100
63/63

### 순환신경망 

In [52]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
model.add(layers.LSTM(50, return_sequences = True))
model.add(layers.LSTM(36,dropout = 0.3))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()
#dropout layer를 추가하고 성능이 좋지못함 

Model: "sequential_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_23 (Embedding)     (None, 200, 50)           500000    
_________________________________________________________________
lstm_18 (LSTM)               (None, 200, 50)           20200     
_________________________________________________________________
lstm_19 (LSTM)               (None, 36)                12528     
_________________________________________________________________
dense_20 (Dense)             (None, 30)                1110      
_________________________________________________________________
dropout_2 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_21 (Dense)             (None, 9)                 279       
Total params: 534,117
Trainable params: 534,117
Non-trainable params: 0
_______________________________________________

In [53]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 32)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 4s 59ms/sample - loss: 2.1961 - acc: 0.0794
Epoch 2/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.1948 - acc: 0.1270
Epoch 3/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.1807 - acc: 0.1746
Epoch 4/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.1628 - acc: 0.2222
Epoch 5/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.1316 - acc: 0.2222
Epoch 6/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.0603 - acc: 0.2381
Epoch 7/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.0683 - acc: 0.2063
Epoch 8/100
63/63 [==============================] - 0s 6ms/sample - loss: 2.0354 - acc: 0.2381
Epoch 9/100
63/63 [==============================] - 0s 5ms/sample - loss: 1.9370 - acc: 0.1905
Epoch 10/100
63/63 [==============================] - 0s 5ms/sample - loss: 1.8764 - acc: 0.2698
Epoch 11/100
63/63

### 양방향 순환신경망 

In [64]:
embedding_dim = 50
model = models.Sequential()
model.add(layers.Embedding(max_words, output_dim = embedding_dim,input_length = maxlen))
model.add(layers.Bidirectional(layers.LSTM(50, return_sequences = True)))
model.add(layers.Bidirectional(layers.LSTM(36, dropout = 0.3)))
model.add(layers.Dense(30, activation = 'relu'))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(9, activation = 'softmax'))
model.summary()

Model: "sequential_31"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_29 (Embedding)     (None, 200, 50)           500000    
_________________________________________________________________
bidirectional_1 (Bidirection (None, 200, 100)          40400     
_________________________________________________________________
bidirectional_2 (Bidirection (None, 72)                39456     
_________________________________________________________________
dense_22 (Dense)             (None, 30)                2190      
_________________________________________________________________
dropout_3 (Dropout)          (None, 30)                0         
_________________________________________________________________
dense_23 (Dense)             (None, 9)                 279       
Total params: 582,325
Trainable params: 582,325
Non-trainable params: 0
_______________________________________________

In [65]:
model.compile(loss = 'categorical_crossentropy', optimizer = 'rmsprop', metrics = ['acc'])
model.fit(X_train, y_train,  epochs = 100, batch_size = 32)

Train on 63 samples
Epoch 1/100
63/63 [==============================] - 7s 111ms/sample - loss: 2.1975 - acc: 0.0635
Epoch 2/100
63/63 [==============================] - 0s 7ms/sample - loss: 2.1933 - acc: 0.1270
Epoch 3/100
63/63 [==============================] - 0s 7ms/sample - loss: 2.1755 - acc: 0.1905
Epoch 4/100
63/63 [==============================] - 0s 7ms/sample - loss: 2.1706 - acc: 0.1587
Epoch 5/100
63/63 [==============================] - 0s 7ms/sample - loss: 2.1473 - acc: 0.1905
Epoch 6/100
63/63 [==============================] - 0s 7ms/sample - loss: 2.1269 - acc: 0.1111
Epoch 7/100
63/63 [==============================] - 0s 7ms/sample - loss: 2.0467 - acc: 0.2063
Epoch 8/100
63/63 [==============================] - 1s 8ms/sample - loss: 1.8859 - acc: 0.3333
Epoch 9/100
63/63 [==============================] - 0s 8ms/sample - loss: 1.8820 - acc: 0.2540
Epoch 10/100
63/63 [==============================] - 0s 8ms/sample - loss: 1.7923 - acc: 0.3492
Epoch 11/100
63/6